spring.application.name=gestion-notes
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_notes_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
gestionnotes.app.jwtSecret=======================GestionNotesSecretKeyByAntigravity======================
gestionnotes.app.jwtExpirationMs=86400000

# Gemini 2.5 API Configuration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=AIzaSyAF5bozsp1uuS5kTXs2iDTMC24tZCziPTo
